### ISSUE TITLE
LICENCE File

### ISSUE THREAD

**Issue by colinjfw** [foundation/inky#103]
There isn't a licence file inside the repository that I could find, I noticed that `package.json` mentions an MIT license. What license is this project under currently?

**Comment by ieugen** [comment]
Hi, I second the question. Please clarify what license of the code. We would like to use it but we don't want to break any licensing terms. 

Thanks,

**Comment by DanielRuf** [comment]
The `license` field in package.json is correct and sufficient. It is MIT licensed.
