### ISSUE TITLE
Spacer not working - outlook does not recognize px on td

### ISSUE THREAD

**Issue by mir3z** [foundation/inky#104]
See this issue: https://foundation.zurb.com/forum/posts/47983-outlook-2010-spacer-issue

When rendering you add height `<td height="'+size+'px"` on td. According to above mentioned issue Outlook does not recognize px and `<spacer />` does not work - which I can confirm.

The best solution seems to add height twice - with px and without it. What do you think?

The same issue in foundation-emails: https://github.com/zurb/foundation-emails/issues/725

**Comment by marcandre** [comment]
Looks good to me
