### ISSUE TITLE
Vulnerability in vinyl-fs used version

### ISSUE THREAD

**Issue by vncdias** [foundation/inky#120]
Hello Inky maintaining team,

I started using Inky in a project and running `npm audit` I realised that there is a vulnerability in a dependency chain. Here is the audit result of project using `inky@^1.3.7`:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ inky                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ inky > vinyl-fs > glob-stream > micromatch > braces          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

I was looking for the best approach to fix that and seems that updating `vinyl-fs` to 3.0.* will do the trick: every other 2.* versions use a vulnerable version of braces at the end, and 3 doesn't. Since it's a major update I suppose the team need to check if there's some change to do to make it still working.

If possible, I can contribute with code too, since I'm interested on see this working in a project that have a vulnerabilities check at their pipeline.

**Comment by jwmunn** [comment]
I've run into this issue as well on my team since we have a dependency on Inky. I've opened a PR to propose a fix. https://github.com/foundation/inky/pull/121

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/security-vulnerability-in-inky/2774/1

**Comment by vncdias** [comment]
Thanks for the PR @jwmunn 
Since I don't know the reason of using vinyl-fs and it's a major upgrade, I wasn't sure about the impacts of just bumping the version, but certainly that does the trick.

**Comment by DanielRuf** [comment]
vinyl-fs is used by gulp. We will check that when we have time.
As gulp is currently a devDependency it's not critical.

**Comment by DanielRuf** [comment]
We will upgrade the dependencies when we find time maintaining this project. Thanks for the heads up.
